spring.application.name=backend

# ==========================================
#  CONFIGURATION POSTGRESQL (PRODUCTION)
# ==========================================
spring.datasource.url=jdbc:postgresql://dpg-d845ub8jo89c73aijgj0-a.virginia-postgres.render.com/mmotors_7zrd?sslmode=require
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=mmotors_7zrd_user
spring.datasource.password=qoIcprMLKupliPUVenG5zq7yYYBr8yDe

# Configuration JPA / Hibernate pour PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# ==========================================
#  CONFIGURATION GÉNÉRALE
# ==========================================
spring.jpa.show-sql=true

# Configuration pour l'envoi d'images
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true